name: SwedenBans
version: '${project.version}'
main: com.redesweden.swedenbans.SwedenBans
authors: [Darekfive, Netherfoam, FabioZumbi12, rachzy]

soft-depend: [HeroChat]

description: "Plugin de banimentos do Rede Sweden, forkado do MaxBans"
website: redesweden.com

permissions:
    swedenbans.ban:
        description: Allows a player to ban others.
        default: op
    swedenbans.unban:
        description: Allows a player to unban others.
        default: op
    swedenbans.tempban:
        description: Allows a player to tempban others.
        default: op
    swedenbans.tempipban:
        description: Allows a player to temp IP ban others.
        default: op
    swedenbans.ipban:
        description: Allows a player to IP ban others
        default: op
    swedenbans.mute:
        description: Allows a player to mute/unmute others.
        default: op
    swedenbans.unmute:
        description: Allows a player to unmute others.
        default: op
    swedenbans.tempmute:
        description: Allows a player to temp mute others.
        default: op
    swedenbans.checkban:
        description: Allows a player to check others ban info
        default: op
    swedenbans.checkban.self:
        description: Allows a player to check their own ban info (and warnings)
        default: true
    swedenbans.checkip:
        descriptions: Allows a player to lookup another players IP address
        default: op
    swedenbans.warn:
        description: Allows a player to give out warnings to others.
        default: op
    swedenbans.unwarn:
        description: Removes the most recent warning from a player
        default: op
    swedenbans.clearwarnings:
        description: Allows a player to delete all warnings for a given player.
        default: op
    swedenbans.kick:
        description: Allows a player to kick others with a reason
        default: op
    swedenbans.reload:
        description: Allows a player to use /mbreload, reloading MaxBans from scratch.
        default: op
    swedenbans.notify:
        description: Allows a player to see the ban notifications
        default: op
    swedenbans.seebroadcast:
        description: Allows a player to see all the broadcasts
        default: not op

commands:
    uuid:
        description: Gets UUID of a player
        usage: /uuid <player>
        aliases: [mbuuid]
    togglechat:
        description: Toggle chat on or off
        usage: /togglechat
        aliases: [mbtogglechat]
    ban:
        description: Bans a player permanently
        usage: /ban <player|IP> [-s] <reason>
        aliases: [mbban]
    unban:
        description: Unbans a player, includes IP bans
        usage: /unban <player|IP>
        aliases: [mbunban]
    tempban:
        description: Bans a player temporarily
        usage: /tempban <player|IP> <time> <timeform> [-s] <reason>
        aliases: [mbtempban]
    tempipban:
        description: Temporarily IP bans a player
        usage: /tempipban <player|IP> <time> <timeform> [-s] <reason>
        aliases: [mbtempipban]
    ipban:
        description: IP bans a player
        usage: /ipban <player|IP> [-s] <reason>
        aliases: [mbipban]
    mute:
        description: Toggles a players mute status
        usage: /mute <player>
        aliases: [mbmute]
    unmute:
        description: Unmutes a player
        usage: /unmute <player>
        aliases: [mbunmute]
    tempmute:
        description: TempMutes a player
        usage: /tempmute <player> <time> <timeform>
        aliases: [mbtempmute]
    checkban:
        description: Reports the status of a user or IP
        usage: /checkban <player|IP>
        aliases: [mbcheckban]
    checkip:
        description: Reports a players IP address
        usage: /checkip <player>
        aliases: [mbcheckip]
    dupeip:
        description: Reports all players from the same IP
        usage: /dupeip <player|IP>
        aliases: [mbdupeip]
    warn:
        description: Warns a player.
        usage: /warn <player> [reason]
        aliases: [mbwarn]
    unwarn:
        description: Removes a players most recent warning
        usage: /unwarn <player>
        aliases: [mbunwarn]
    clearwarnings:
        description: Clears a players warning history
        usage: /clearwarnings <player>
        aliases: [mbclearwarnings]
    kick:
        description: Kicks a player from the game.
        usage: /kick <player> [reason]
        aliases: [mbkick]
    lockdown:
        description: Prevents anyone without swedenbans.lockdown.bypass from joining.
        usage: /lockdown [reason]
        aliases: [mblockdown]
    history:
        description: Reports any recent bans etc
        usage: /history [name] [records]
        aliases: [mbhistory]
    forcespawn:
        description: Teleports a player to the spawn.
        usage: /forcespawn <player>
        aliases: [mbforcespawn]
    mbreload:
        description: Reloads MaxBans entirely
        usage: /mbreload
    mb:
        description: Displays MaxBans commands that you have access to
        usage: /mb
        aliases: [swedenbans]
    mbimport:
        description: Imports a set of bans
        usage: /mbimport nameOfPlugin
    mbexport:
        description: Exports a set of bans, also allows exporting to another database
        usage: /mbexport nameOfPlugin
    mbdebug:
        description: Print debug info to Console/File/Chat.
        usage: /mbdebug File|Chat|Console
    rangeban:
        description: Ban IP Ranges
        usage: /rangeban <IP1-IP2> [Reason]
        aliases: [mbrangeban, rb]
    temprangeban:
        description: 
        usage: /temprangeban <IP1-IP2> <time> <timeform> [Reason]
        aliases: [mbtemprangeban, temprb]
    unrangeban:
        description: Unbans an IP range. The given IP only needs to be inside a range.
        usage: /unrangeban <IP>
        aliases: [mbunrangeban, unrb]
    mbwhitelist:
        description: Whitelisting command, allowing players to bypass IP bans (Not regular bans)
        usage: /mbwhitelist <user>
    immune:
        description: Allows/Disallows punishment immunity for a user
        usage: /immune <user> <true|false>
        aliases: [mbimmune]